- name: setup a go build
  block:
    - name: install go dependencies for build
      command: make install

    - name: create directory for build
      command: make builddir

    - name: build for deployment
      command: make build

    - name: zip build for deployment
      command: make zip
      when: "{{ make_zip }}"

  args:
    chdir: "{{ work_dir }}"
