- name: publish coffeelint-config-suddi to npm
  hosts: local
  gather_facts: no

  vars:
    repo_name: coffeelint-config-suddi
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

  roles:
    - role: publish_npm_package
      tags:
          - publish
          - npm
