- name: publish object-to-object-mapper to npm
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ general_project_name }}"
    package_name: object-to-object-mapper
    service_name: "{{ general_service_prefix }}npm-{{ package_name }}"
    service_url: https://www.npmjs.com/package/{{ package_name }}

    repo_name: "node-{{ package_name }}"
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

    deploy_user: "{{ runtime_user }}"

    node_version: v6

  roles:
    - role: assert_node_version
      expected_node_version: "{{ node_version }}"

    - role: empty_work_dir

    - role: publish_npm_package
      tags:
          - publish
          - npm

    - role: empty_work_dir

    - role: notify_knightwatcher
      message_username: "{{ deploy_user }}"
      message_type: npm-publish
      message_link: "{{ service_url }}"
      message_repo_name: "{{ repo_name }}"
