- name: install macos dependencies
  block:
    - name: install xcode dependencies
      command: xcode-select --install
      register: xcode_install_result
      failed_when: "xcode_install_result.rc != 0 and
        'command line tools are already installed' not in xcode_install_result.stderr"

    - name: install homebrew
      block:
        - name: check if homebrew is installed
          stat:
            path: /usr/local/bin/brew
          register: homebrew_check

        - name: install homebrew
          command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          when: not homebrew_check.stat.exists

        - name: update brew
          command: brew update

    - name: install {{ item }}
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ brew_dependencies }}"

  when: ansible_facts["os_family"] == "Darwin"
