- name: install macos dependencies
  block:
    - name: print applications to install as a reminder
      debug:
        msg: "Make sure to install the following:\n{{ applications_to_install | to_nice_yaml }}"

    - name: install homebrew
      block:
        - name: check if homebrew is installed
          stat:
            path: /usr/local/bin/brew
          register: homebrew_check

        - name: install homebrew
          command: mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
          when: not homebrew_check.stat.exists

  when: ansible_facts["os_family"] == "Darwin"
