- name: create download directory
  file:
    state: directory
    mode: "0644"
    dest: "{{ golang_download_dir }}"

- name: download golang
  get_url:
    url: "{{ golang_mirror }}/{{ golang_dist_filename }}"
    dest: "{{ golang_download_dir }}/{{ golang_redis_filename }}"
    sha256sum: "{{ golang_dist_checksum }}"
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: "0644"

- name: create golang installation directory
  file:
    state: directory
    owner: root
    group: root
    mode: "0755"
    dest: "{{ golang_install_dir }}"
  become: yes

- name: install golang
  unarchive:
    src: "{{ golang_download_dir }}/{{ golang_dist_filename }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    dest: "{{ golang_install_dir }}"
    owner: root
    group: root
    creates: "{{ golang_install_dir }}/bin"
  become: yes

- name: make sure /etc/profile.d exists
  file:
    path: /etc/profile.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: export golang environment variables
  template:
    src: golang.sh.j2
    dest: /etc/profile.d/golang.sh
    owner: root
    group: root
    mode: "0644"
  become: yes
