- name: eslint-config-suddi
  hosts: local
  gather_facts: no

  vars:
    repo_name: eslint-config-suddi
    repo_url: git@github.com:suddi/eslint-config-suddi.git
    temp_dir: "{{ work_dir }}/{{ repo_name }}"
    version: master
    version_increment_level: "{{ update_type | default('patch') }}"

  pre_tasks:
    - assert:
        that: "version_increment_level in ['major', 'minor', 'patch']"

  tasks:
    - name: publish {{ repo_name }} to NPM
      include_role:
        name: common
