version: 2

jobs:
  node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)

  python:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user --requirement requirements.txt --requirement test_requirements.txt
      - run: python setup.py lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - node12
      - python

notify:
  webhooks:
    - url: https://bot.suddi.io/hooks/circle
