- name: install git
  apt:
    autoclean: yes
    autoremove: yes
    name: git
    state: present
  become: yes
  when: "{{ dependency_git_install }}"

- name: set git user
  command: git config --global user.name "{{ user }}"
  when: "{{ dependency_git_install }}"

- name: set git user email
  command: git config --global user.email "{{ user }}@{{ user_machine_name }}"
  when: "{{ dependency_git_install }}"

- name: set git editor
  command: git config --global core.editor "nano"
  when: "{{ dependency_git_install }}"

- name: set git push nature
  command: git config --global push.default simple
  when: "{{ dependency_git_install }}"

- name: install make
  apt:
    autoclean: yes
    autoremove: yes
    name: make
    state: present
  become: yes
  when: "{{ dependency_make_install }}"

- name: install zsh
  apt:
    autoclean: yes
    autoremove: yes
    name: zsh
    state: present
  become: yes
  when: "{{ dependency_zsh_install }}"
