# ------------------------------------------------------------------------------
# GENERAL
# ------------------------------------------------------------------------------
deployment_method: ansible
sensitive_files:
  - group_vars/all/vault.encrypted.yml
  - inventory.ini

github_url: "{{ vault_github_url }}"
linkedin_url: "{{ vault_linkedin_url }}"

# ------------------------------------------------------------------------------
# DIRECTORIES
# ------------------------------------------------------------------------------
project_root_dir: "{{ inventory_dir }}"
files_dir: "{{ inventory_dir }}/files"
temp_dir: "{{ inventory_dir }}/tmp"
# NOTE: "repo_name" needs to be specified in order to use "work_dir"
work_dir: "{{ temp_dir }}/{{ repo_name }}"

# ------------------------------------------------------------------------------
# VERSION CONTROL
# ------------------------------------------------------------------------------
github_account: "{{ vault_github_account }}"
bitbucket_account: "{{ vault_bitbucket_account }}"

# ------------------------------------------------------------------------------
# DEFAULT USER SPECIFICS
# ------------------------------------------------------------------------------
default_user: "{{ vault_default_user }}"
default_user_email: "{{ vault_default_user_email }}"

# AWS
default_user_aws_access_key_id: "{{ vault_default_user_aws_access_key_id }}"
default_user_aws_secret_access_key: "{{ vault_default_user_aws_secret_access_key }}"

default_user_aws_profile: "{{ vault_default_user_aws_profile }}"
default_user_aws_region: "{{ vault_default_user_aws_region }}"

# ------------------------------------------------------------------------------
# RUNTIME USER SPECIFICS
# ------------------------------------------------------------------------------
runtime_user: "{{ lookup('env', 'USER') }}"
runtime_user_home_dir: "{{ lookup('env', 'HOME') }}"

# ------------------------------------------------------------------------------
# DEPLOYMENT USER SPECIFICS
# ------------------------------------------------------------------------------
deployment_user: deploy
deployment_user_home_dir: /home/deploy

# ------------------------------------------------------------------------------
# CICD USER SPECIFICS
# ------------------------------------------------------------------------------
cicd_user: jenkins
cicd_user_home_dir: /var/lib/jenkins
cicd_user_machine_name: cicd

# AWS
cicd_user_aws_access_key_id: "{{ vault_cicd_user_aws_access_key_id }}"
cicd_user_aws_secret_access_key: "{{ vault_cicd_user_aws_secret_access_key }}"

# NPM
cicd_user_npm_auth_token: "{{ vault_cicd_user_npm_auth_token }}"

# ------------------------------------------------------------------------------
# DOMAINS
# ------------------------------------------------------------------------------
github_domain: "{{ vault_github_domain }}"
lambda_domain: "{{ vault_lambda_domain }}"
linkedin_domain: "{{ vault_linkedin_domain }}"
vault_domain: "{{ vault_vault_domain }}"

# ------------------------------------------------------------------------------
# PROJECTS
# ------------------------------------------------------------------------------
# General
general_project_name: suddi
general_service_url: "{{ vault_general_service_url }}"
general_domain: "{{ vault_general_domain }}"

# Knightwatcher
knightwatcher_project_name: knightwatcher
knightwatcher_service_url: "{{ vault_knightwatcher_service_url }}"

knightwatcher_config_aws_region: ap-northeast-1
knightwatcher_config_tablename: "{{ vault_knightwatcher_config_tablename }}"
knightwatcher_config_telegram_api_key: "{{ vault_knightwatcher_config_telegram_api_key }}"
knightwatcher_config_default_notifier: "{{ vault_knightwatcher_config_default_notifier }}"

# Kobe
kobe_project_name: kobe
kobe_service_url: "{{ vault_kobe_service_url }}"

kobe_config_microsoft_app_id: "{{ vault_kobe_config_microsoft_app_id }}"
kobe_config_microsoft_app_password: "{{ vault_kobe_config_microsoft_app_password }}"

# MemoriesBot
memoriesbot_project_name: memoriesbot
memoriesbot_service_url: "{{ vault_memoriesbot_service_url }}"

memoriesbot_config_telegram_api_key: "{{ vault_memoriesbot_config_telegram_api_key }}"

memoriesbot_aws_lambda_role_name: "{{ vault_memoriesbot_aws_lambda_role_name }}"

# CICD
cicd_project_name: cicd
cicd_service_url: "{{ vault_cicd_service_url }}"

# BuildGreenr
buildgreenr_project_name: buildgreenr
buildgreenr_service_url: "{{ vault_buildgreenr_service_url }}"

# OnePusher
onepusher_project_name: onepusher
onepusher_service_url: "{{ vault_onepusher_service_url }}"

# ThinkTech Industries
thinktechindustries_project_name: thinktechindustries
thinktechindustries_domain: "{{ vault_thinktechindustries_domain }}"

# ------------------------------------------------------------------------------
# SOFTWARE RUNTIME VERSIONS
# ------------------------------------------------------------------------------
node_version: v12
python_version: "3.8"
go_version: "1.14"

# ------------------------------------------------------------------------------
# PACKAGE VERSIONS
# ------------------------------------------------------------------------------
# This should be kept in sync with requirements.txt
ansible_version: "2.4.0.0"
awscli_version: "1.11.166"
boto_version: "2.48.0"
boto3_version: "1.4.7"
python_dateutil_version: "2.6.1"
pyOpenSSL_version: "17.3.0"
# ------------------------------------------------------------------------------
