# ------------------------------------------------------------------------------
# GENERAL
# ------------------------------------------------------------------------------
deployment_method: ansible
sensitive_files:
  - group_vars/all/vault.encrypted.yml
  - inventory.ini

github_url: "{{ vault_github_url }}"
linkedin_url: "{{ vault_linkedin_url }}"

aws_profile: default
aws_region: ap-northeast-1

pypi_username: "{{ vault_pypi_username }}"
pypi_password: "{{ vault_pypi_password }}"

# ------------------------------------------------------------------------------
# DIRECTORIES
# ------------------------------------------------------------------------------
project_root_dir: "{{ inventory_dir }}"
files_dir: "{{ inventory_dir }}/files"
temp_dir: "{{ inventory_dir }}/tmp"
# NOTE: "repo_name" needs to be specified in order to use "work_dir"
work_dir: "{{ temp_dir }}/{{ repo_name }}"

# ------------------------------------------------------------------------------
# VERSION CONTROL
# ------------------------------------------------------------------------------
github_account: "{{ vault_github_account }}"
bitbucket_account: "{{ vault_bitbucket_account }}"

thinktech_github_account: "{{ vault_thinktech_github_account }}"

# ------------------------------------------------------------------------------
# RUNTIME USER SPECIFICS
# ------------------------------------------------------------------------------
runtime_user: "{{ lookup('env', 'USER') }}"
runtime_user_home_dir: "{{ lookup('env', 'HOME') }}"

# ------------------------------------------------------------------------------
# DEFAULT USER SPECIFICS
# ------------------------------------------------------------------------------
default_user: "{{ vault_default_user }}"
default_user_email: "{{ vault_default_user_email }}"

# AWS
default_user_aws_access_key_id: "{{ vault_default_user_aws_access_key_id }}"
default_user_aws_secret_access_key: "{{ vault_default_user_aws_secret_access_key }}"

# ------------------------------------------------------------------------------
# CICD USER SPECIFICS
# ------------------------------------------------------------------------------
cicd_user: "{{ vault_cicd_user }}"
cicd_user_home_dir: "{{ vault_cicd_home_dir }}"
cicd_user_machine_name: "{{ vault_cicd_user_machine_name }}"

# AWS
cicd_user_aws_access_key_id: "{{ vault_cicd_user_aws_access_key_id }}"
cicd_user_aws_secret_access_key: "{{ vault_cicd_user_aws_secret_access_key }}"

# NPM
cicd_user_npm_auth_token: "{{ vault_cicd_user_npm_auth_token }}"

# ------------------------------------------------------------------------------
# PROJECTS
# ------------------------------------------------------------------------------
# General
general_project_name: suddi
general_domain: "{{ vault_general_domain }}"
github_domain: "{{ vault_github_domain }}"
lambda_domain: "{{ vault_lambda_domain }}"
linkedin_domain: "{{ vault_linkedin_domain }}"
vault_domain: "{{ vault_vault_domain }}"
general_service_url: "{{ vault_general_service_url }}"

# Knightwatcher
knightwatcher_project_name: knightwatcher
knightwatcher_service_url: "{{ vault_knightwatcher_service_url }}"

knightwatcher_config_aws_region: "{{ vault_knightwatcher_config_aws_region }}"
knightwatcher_config_tablename: "{{ vault_knightwatcher_config_tablename }}"
knightwatcher_config_telegram_api_key: "{{ vault_knightwatcher_config_telegram_api_key }}"
knightwatcher_config_default_notifier: "{{ vault_knightwatcher_config_default_notifier }}"

# Kobe
kobe_project_name: kobe
kobe_service_url: "{{ vault_kobe_service_url }}"

kobe_config_microsoft_app_id: "{{ vault_kobe_config_microsoft_app_id }}"
kobe_config_microsoft_app_password: "{{ vault_kobe_config_microsoft_app_password }}"

# MemoriesBot
memoriesbot_project_name: memoriesbot
memoriesbot_service_url: "{{ vault_memoriesbot_service_url }}"

memoriesbot_config_telegram_api_key: "{{ vault_memoriesbot_config_telegram_api_key }}"

memoriesbot_aws_lambda_role_name: "{{ vault_memoriesbot_aws_lambda_role_name }}"

# CICD
cicd_project_name: cicd
cicd_service_url: "{{ vault_cicd_service_url }}"

# BuildGreenr
buildgreenr_project_name: buildgreenr
buildgreenr_service_url: "{{ vault_buildgreenr_service_url }}"

# OnePusher
onepusher_project_name: onepusher
onepusher_service_url: "{{ vault_onepusher_service_url }}"

# Sudharsya
sudharsya_project_name: sudharsya
sudharsya_domain: "{{ vault_sudharsya_domain }}"
sudharsya_service_url: "{{ vault_sudharsya_service_url }}"

sudharsya_certificate_arn: "{{ vault_sudharsya_certificate_arn }}"

# ThinkTech Industries
thinktechindustries_project_name: thinktechindustries
thinktechindustries_domain: "{{ vault_thinktechindustries_domain }}"
thinktechindustries_service_url: "{{ vault_thinktechindustries_service_url }}"

thinktechindustries_certificate_arn: "{{ vault_thinktechindustries_certificate_arn }}"

# ------------------------------------------------------------------------------
# SOFTWARE RUNTIME VERSIONS
# ------------------------------------------------------------------------------
node_version: v12
python_version: "3.8"
go_version: "1.14"

# ------------------------------------------------------------------------------
# PACKAGE VERSIONS
# ------------------------------------------------------------------------------
# This should be kept in sync with requirements.txt
ansible_version: "2.9.7"
awscli_version: "1.18.39"
boto_version: "2.49.0"
boto3_version: "1.12.39"
python_dateutil_version: "2.8.1"
pyOpenSSL_version: "19.1.0"

# ------------------------------------------------------------------------------
