# ------------------------------------------------------------------------------
# GENERAL
# ------------------------------------------------------------------------------
deployment_method: ansible
sensitive_files:
  - group_vars/all/vault.encrypted.yml
  - inventory.ini

# ------------------------------------------------------------------------------
# DIRECTORIES
# ------------------------------------------------------------------------------
project_root_dir: "{{ inventory_dir }}"
files_dir: "{{ inventory_dir }}/files"
temp_dir: "{{ inventory_dir }}/tmp"
# NOTE: "repo_name" needs to be specified in order to use "work_dir"
work_dir: "{{ temp_dir }}/{{ repo_name }}"

# ------------------------------------------------------------------------------
# VERSION CONTROL
# ------------------------------------------------------------------------------
github_account: "{{ vault_github_account }}"
bitbucket_account: "{{ vault_bitbucket_account }}"

# ------------------------------------------------------------------------------
# RUNTIME USER SPECIFICS
# ------------------------------------------------------------------------------
runtime_user: "{{ lookup('env', 'USER') }}"
runtime_user_home_dir: "{{ lookup('env', 'HOME') }}"

# ------------------------------------------------------------------------------
# DEPLOYMENT USER SPECIFICS
# ------------------------------------------------------------------------------
deployment_user: deploy
deployment_user_home_dir: /home/deploy

# ------------------------------------------------------------------------------
# CICD USER SPECIFICS
# ------------------------------------------------------------------------------
cicd_user: jenkins
cicd_user_home_dir: /var/lib/jenkins
cicd_user_machine_name: cicd

# AWS
cicd_user_aws_access_key_id: "{{ vault_cicd_user_aws_access_key_id }}"
cicd_user_aws_secret_access_key: "{{ vault_cicd_user_aws_secret_access_key }}"

# NPM
cicd_user_npm_auth_token: "{{ vault_cicd_user_npm_auth_token }}"

# ------------------------------------------------------------------------------
# PROJECTS
# ------------------------------------------------------------------------------
# General
general_project_name: suddi
general_service_prefix: "{{ general_project_name }}-"
general_service_url: "{{ vault_general_service_url }}"
general_aws_profile: suddi

# Knightwatcher
knightwatcher_project_name: knightwatcher
knightwatcher_service_prefix: "{{ knightwatcher_project_name }}-"
knightwatcher_service_url: "{{ vault_knightwatcher_service_url }}"

knightwatcher_config_aws_region: ap-northeast-1
knightwatcher_config_tablename: "{{ vault_knightwatcher_config_tablename }}"
knightwatcher_config_telegram_api_key: "{{ vault_knightwatcher_config_telegram_api_key }}"
knightwatcher_config_default_notifier: "{{ vault_knightwatcher_config_default_notifier }}"

# Kobe
kobe_project_name: kobe
kobe_service_prefix: "{{ kobe_project_name }}-"
kobe_service_url: "{{ vault_kobe_service_url }}"

kobe_config_microsoft_app_id: "{{ vault_kobe_config_microsoft_app_id }}"
kobe_config_microsoft_app_password: "{{ vault_kobe_config_microsoft_app_password }}"

# CICD
cicd_project_name: cicd
cicd_service_prefix: "{{ cicd_project_name }}-"
cicd_service_url: "{{ vault_cicd_service_url }}"

# BuildGreenr
buildgreenr_project_name: buildgreenr
buildgreenr_service_prefix: "{{ buildgreenr_project_name }}-"
buildgreenr_service_url: "{{ vault_buildgreenr_service_url }}"

# OnePusher
onepusher_project_name: onepusher
onepusher_service_prefix: "{{ onepusher_project_name }}-"
onepusher_service_url: "{{ vault_onepusher_service_url }}"

# ThinkTech Industries
thinktech_industries_project_name: thinktech_industries
thinktech_industries_service_prefix: "{{ thinktech_industries_project_name }}-"
thinktech_industries_service_url: "{{ vault_thinktech_industries_service_url }}"

# ------------------------------------------------------------------------------
# PACKAGE VERSIONS
# ------------------------------------------------------------------------------
# This should be kept in sync with requirements.txt
ansible_version: "2.4.0.0"
awscli_version: "1.11.166"
boto_version: "2.48.0"
boto3_version: "1.4.7"
python_dateutil_version: "2.6.1"
pyOpenSSL_version: "17.3.0"

# ------------------------------------------------------------------------------
