- name: get source code
  git:
    repo: "{{ repo_url }}"
    dest: "{{ work_dir }}"
    force: yes
    update: yes
    version: "{{ repo_version }}"
  register: git_result

- name: store git commit hash
  set_fact:
    deployment_version: "{{ git_result.after | truncate(7, True, '') }}"
