---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create certificates in US-East-1

Parameters:
  ProjectName:
    Description: Project name for the resources under this CloudFormation template
    Type: String
  ServiceName:
    Description: Service name prefix for the resources under this CloudFormation template
    Type: String
  DeployedBy:
    Description: Deployment user/service
    Type: String
    Default: ansible
  Domain:
    Description: Domain for this service
    Type: String

Resources:
# ------------------------------------------------------------------------------
# CERTIFICATES
# ------------------------------------------------------------------------------
  ThinkTechIndustriesCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          ValidationDomain: !Ref Domain
        - DomainName: !Sub www.${Domain}
          ValidationDomain: !Ref Domain
      SubjectAlternativeNames:
        - !Sub www.${Domain}
      ValidationMethod: EMAIL
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-certificate
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: DeployedBy
          Value: !Ref DeployedBy

# ------------------------------------------------------------------------------
