---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create resources for github.suddi.io

Parameters:
  Project:
    Description: Project that the resources in this CloudFormation template is for
    Type: String
  Service:
    Description: Service that the resources in this CloudFormation template is for
    Type: String
  DeployedBy:
    Description: Deployment user/service
    Type: String
    Default: ansible
  RouteUrl:
    Description: URL to redirect requests to
    Type: String
  HostedZone:
    Description: Name of the hosted zone in Route 53
    Type: String

Mappings:
  RegionMap:
    # US East (North Virginia)
    us-east-1:
      S3WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
      HostedZoneId: Z3AQBSTGFYJSTF
    # US East (Ohio)
    us-east-2:
      S3WebsiteEndpoint: s3-website.us-east-2.amazonaws.com
      HostedZoneId: Z2O1EMRO9K5GLX
    # US West (Northern California)
    us-west-1:
      S3WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
      HostedZoneId: Z2F56UZL2M1ACD
    # US West (Oregon)
    us-west-2:
      S3WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
      HostedZoneId: Z3BJ6K6RIION7M
    # Asia Pacific (Hong Kong)
    ap-east-1:
      S3WebsiteEndpoint: s3-website.ap-east-1.amazonaws.com
      HostedZoneId: ZNB98KWMFR0R6
    # Asia Pacific (Tokyo)
    ap-northeast-1:
      S3WebsiteEndpoint: s3-website-ap-northeast-1.amazonaws.com
      HostedZoneId: Z2M4EHUR26P7ZW
    # Asia Pacific (Seoul)
    ap-northeast-2:
      S3WebsiteEndpoint: s3-website.ap-northeast-2.amazonaws.com
      HostedZoneId: Z3W03O7B5YMIYP
    # Asia Pacific (Osaka)
    ap-northeast-3:
      S3WebsiteEndpoint: s3-website.ap-northeast-3.amazonaws.com
      HostedZoneId: Z2YQB5RD63NC85
    # Asia Pacific (Mumbai)
    ap-south-1:
      S3WebsiteEndpoint: s3-website.ap-south-1.amazonaws.com
      HostedZoneId: Z11RGJOFQNVJUP
    # Asia Pacific (Singapore)
    ap-southeast-1:
      S3WebsiteEndpoint: s3-website-ap-southeast-1.amazonaws.com
      HostedZoneId: Z3O0J2DXBE1FTB
    # Asia Pacific (Sydney)
    ap-southeast-2:
      S3WebsiteEndpoint: s3-website-ap-southeast-2.amazonaws.com
      HostedZoneId: Z1WCIGYICN2BYD
    # Canada (Central)
    ca-central-1:
      S3WebsiteEndpoint: s3-website.ca-central-1.amazonaws.com
      HostedZoneId: Z1QDHH18159H29
    # China (Ningxia)
    cn-northwest-1:
      S3WebsiteEndpoint: s3-website.cn-northwest-1.amazonaws.com.cn
      # HostedZoneId: Not Supported
    # Europe Central (Frankfurt)
    eu-central-1:
      S3WebsiteEndpoint: s3-website.eu-central-1.amazonaws.com
      HostedZoneId: Z21DNDUVLTQW6Q
    # Europe West (Ireland)
    eu-west-1:
      S3WebsiteEndpoint: s3-website-eu-west-1.amazonaws.com
      HostedZoneId: Z1BKCTXD74EZPE
    # Europe West (London)
    eu-west-2:
      S3WebsiteEndpoint: s3-website.eu-west-2.amazonaws.com
      HostedZoneId: Z3GKZC51ZF0DB4
    # Europe West (Paris)
    eu-west-3:
      S3WebsiteEndpoint: s3-website.eu-west-3.amazonaws.com
      HostedZoneId: Z3R1K369G5AVDG
    # Europe North (Stockholm)
    eu-north-1:
      S3WebsiteEndpoint: s3-website.eu-north-1.amazonaws.com
      HostedZoneId: Z3BAZG2TWCNX0D
    # South America (São Paulo)
    sa-east-1:
      S3WebsiteEndpoint: s3-website-sa-east-1.amazonaws.com
      HostedZoneId: Z7KQH4QJS55SO
    # Middle East (Bahrain)
    me-south-1:
      S3WebsiteEndpoint: s3-website.me-south-1.amazonaws.com
      HostedZoneId: Z1MPMWCPA7YB62

Resources:
# ------------------------------------------------------------------------------
# S3 BUCKET
# ------------------------------------------------------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Service
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RouteUrl
          Protocol: https
      Tags:
        - Key: Name
          Value: !Ref Service
        - Key: Project
          Value: !Ref Project
        - Key: Service
          Value: !Ref Service
        - Key: DeployedBy
          Value: !Ref DeployedBy

# ------------------------------------------------------------------------------
# ROUTE 53 RECORDSET
# ------------------------------------------------------------------------------
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: S3Bucket
    Properties:
      HostedZoneName: !Ref HostedZone
      Name: !Ref Service
      AliasTarget:
        DNSName: !FindInMap
          - RegionMap
          - !Ref AWS::Region
          - S3WebsiteEndpoint
        HostedZoneId: !FindInMap
          - RegionMap
          - !Ref AWS::Region
          - HostedZoneId
      Type: A

# ------------------------------------------------------------------------------
