---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: CloudFormation template to create resources for suddi.io

  Parameters:
    ProjectName:
      Description: Project name for the resources under this CloudFormation template
      Type: String
    ServiceName:
      Description: Service name prefix for the resources under this CloudFormation template
      Type: String
    DeployedBy:
      Description: Deployment user/service
      Type: String
      Default: ansible
    Domain:
      Description: Domain for this service
      Type: String
    HostedZone:
      Description: Name of the hosted zone in Route 53
      Type: String
    MailAdministrator:
      Description: Email address of the mail administrator for DMARC record
      Type: String

  Resources:
  # ------------------------------------------------------------------------------
  # ROUTE 53 RECORDSETS
  # ------------------------------------------------------------------------------
    DmarcRoute53RecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: !Ref HostedZone
        Name: !Sub "_dmarc.${Domain}"
        ResourceRecords:
          - !Sub '"v=DMARC1; p=quarantine; rua=mailto:${MailAdministrator}"'
        TTL: "300"
        Type: TXT

    GoogleSiteVerificationRoute53RecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: !Ref HostedZone
        Name: !Ref Domain
        ResourceRecords:
          - '"v=spf1 include:mailgun.org ~all"'
          - '"google-site-verification={{ google_site_verification_text }}"'
        TTL: "300"
        Type: TXT

# ------------------------------------------------------------------------------
