---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create resources for vault.suddi.io

Parameters:
  Project:
    Description: Project that the resources in this CloudFormation template is for
    Type: String
  Service:
    Description: Service that the resources in this CloudFormation template is for
    Type: String
  DeployedBy:
    Description: Deployment user/service
    Type: String
    Default: ansible

Resources:
# ------------------------------------------------------------------------------
# S3 BUCKETS
# ------------------------------------------------------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Service
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref Service
        - Key: Project
          Value: !Ref Project
        - Key: Service
          Value: !Ref Service
        - Key: DeployedBy
          Value: !Ref DeployedBy

# ------------------------------------------------------------------------------
