---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create resources for vault.suddi.io

Parameters:
  ProjectName:
    Description: Project name for the resources under this CloudFormation template
    Type: String
  ServiceName:
    Description: Service name prefix for the resources under this CloudFormation template
    Type: String
  DeployedBy:
    Description: Deployment user/service
    Type: String
    Default: ansible
  Domain:
    Description: Domain for this service
    Type: String

Resources:
# ------------------------------------------------------------------------------
# S3 BUCKETS
# ------------------------------------------------------------------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Domain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-bucket
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: !Ref ServiceName
        - Key: DeployedBy
          Value: !Ref DeployedBy

# ------------------------------------------------------------------------------
