brew_dependencies:
  # for jumping through file paths
  - fasd 
  # for version control
  - git
  # for ssh
  - openssl
  # for gpg
  - gnupg
  - gnupg2
  - pinentry-mac
  # general
  - make
  - wget
  # for python
  - readline
  - sqlite3
  - xz
  - zlib
  - pyenv
  - pyenv-virtualenvwrapper
  # shell
  - zsh