# NOTE: This play is still a work in progress
- name: jenkins
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ cicd_project_name }}"
    service_name: "{{ cicd_service_prefix }}jenkins"
    service_url: "{{ cicd_service_url }}"

    gcp_region: us-east1-d
    gcp_project_name: "{{ project_name }}"
    gcp_project_id: "{{ gcp_project_name }}-181808"
    gcp_gce_instance_type: f1-micro
    gcp_gce_disk_size: 30

    jenkins_image: jenkins-home
    jenkins_image_url: https://storage.googleapis.com/solutions-public-assets/jenkins-cd/jenkins-home-v3.tar.gz

  tasks:
    - name: get {{ jenkins_image }} image
      command: gcloud compute images describe {{ jenkins_image }}
      register: get_image_result
      failed_when: "get_image_result.stderr and
        'was not found' not in get_image_result.stderr"

    - name: download {{ jenkins_image }} image
      command: gcloud compute images create {{ jenkins_image }}
        --source-uri {{ jenkins_image_url }}
        --labels service={{ service_name }},deployment-method={{ deployment_method }},project={{ gcp_project_name }}
      when: "get_image_result.stderr and
        'was not found' in get_image_result.stderr"

    - name: get {{ jenkins_image }} disk
      command: gcloud compute disks describe {{ jenkins_image }}
        --zone {{ gcp_region }}
      register: get_disk_result
      failed_when: "get_disk_result.stderr and
        'was not found' not in get_disk_result.stderr and
        'HTTPError 404' not in get_disk_result.stderr"

    - name: create {{ jenkins_image }} disk
      command: gcloud compute disks create {{ jenkins_image }}
        --image {{ jenkins_image }}
        --labels service={{ service_name }},deployment-method={{ deployment_method }},project={{ gcp_project_name }}
        --size {{ gcp_gce_disk_size }}
        --zone {{ gcp_region }}
      when: "get_disk_result.stderr and
        'was not found' in get_disk_result.stderr and
        'HTTPError 404' in get_disk_result.stderr"

    - name: get {{ service_name }} instance
      command: gcloud compute instances describe {{ service_name }}
        --zone {{ gcp_region }}
      register: get_instance_result
      failed_when: "get_instance_result.stderr and
        'was not found' not in get_instance_result.stderr"

    - name: create {{ service_name }} instance
      command: gcloud compute instances create {{ service_name }}
        --disk name={{ jenkins_image }}
        --machine-type {{ gcp_gce_instance_type }}
        --labels service={{ service_name }},deployment-method={{ deployment_method }},project={{ gcp_project_name }}
        --zone {{ gcp_region }}
      when: "get_instance_result.stderr and
        'was not found' in get_instance_result.stderr"
