- name: generate private key file {{ ssh_key_file }}
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_comment: "{{ user }}@{{ user_machine_name | lower }}"
    ssh_key_file: "{{ ssh_directory }}/{{ ssh_key_file }}"
    ssh_key_type: rsa
    state: present

- name: read public key file {{ ssh_pub_key_file }}
  command: cat "{{ user_home_dir }}/{{ ssh_directory }}/{{ ssh_pub_key_file }}"
  register: cat_public_key_file_result
  changed_when: no

- name: print public key file {{ ssh_pub_key_file }}
  debug:
    var: cat_public_key_file_result.stdout
