- name: create lambda-functions-bucket to house zipped lambda functions
  hosts: local
  gather_facts: no

  vars:
    project_name: lambda-functions
    service_name: "{{ lambda_functions_bucket }}"

    aws_profile: "{{ default_user_aws_profile }}"
    aws_region: "{{ default_user_aws_region }}"

  roles:
    - role: aws/execute_cloudformation_stack
      aws_stack_name: "{{ project_name }}-bucket-stack"
      aws_stack_file_path: "{{ files_dir }}/cloudformation/create_s3_bucket.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ service_name }}
