- name: create new group {{ user }} if it does not exist
  group:
    name: "{{ user }}"
    state: present
  become: yes

- name: create new user {{ user }} if it does not exist
  user:
    createhome: yes
    expires: no
    force: no
    group: "{{ user }}"
    home: "{{ user_home_dir }}"
    name: "{{ user }}"
    state: present
  become: yes
