- name: setup cicd server
  hosts: cicd
  gather_facts: no

  vars:
    machine_name: cicd
    ssh_key_file: id_rsa
    ssh_user: jenkins
    ssh_user_home_dir: /var/lib/jenkins

    node_versions:
      - "4"
      - "6"
      - "8"

    repo_url: git@github.com:suddi/playbooks.git
    repo_dir: "{{ ssh_user_home_dir }}/playbooks"
    version: master

  roles:
    - role: install_general_dependencies
      become: yes
      tags:
        - packages

    - role: install_python_dependencies
      become: yes
      tags:
        - packages
        - python

    - role: generate_ssh_keys
      become: yes
      become_user: "{{ ssh_user }}"
      tags:
        - ssh

    - role: install_node_dependencies
      become: yes
      become_user: "{{ ssh_user }}"
      tags:
        - packages
        - node

  tasks:
    - name: clone playbooks repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        force: yes
        version: "{{ version }}"
      become: yes
      become_user: "{{ ssh_user }}"

    - name: pip install dependencies
      command: pip install
        --requirement requirements.txt
      args:
        chdir: "{{ repo_dir }}"
      become: yes

    - name: npm install
      shell: source {{ ssh_user_home_dir }}/.nvm/nvm.sh; npm install
      args:
        chdir: "{{ repo_dir }}"
        executable: /bin/bash
      become: yes
      become_user: "{{ ssh_user }}"
