- name: setup cicd server
  hosts: "{{ variable_host | default('cicd') }}"
  gather_facts: no

  vars:
    project_name: "{{ cicd_project_name }}"
    service_name: "{{ cicd_service_prefix }}cicd"
    service_url: "{{ cicd_service_url }}"

    repo_name: playbooks
    repo_url: "{{ github_account }}/playbooks.git"

    work_dir: "{{ cicd_user_home_dir }}/playbooks"

    user: "{{ cicd_user }}"
    user_home_dir: "{{ cicd_user_home_dir }}"
    user_machine_name: "{{ cicd_user_machine_name }}"
    user_shell: /bin/bash
    user_shell_profile_file: "{{ deploy_user_home_dir }}/.bash_profile"
    user_shell_rc_file: "{{ deploy_user_home_dir }}/.bashrc"

    python_versions:
      - "2.7.17"
      - "3.8.2"
    python_default_version: "{{ python_versions[0] }}"

    node_versions:
      - "8"
      - "10"
      - "12"
    node_default_version: "{{ node_versions[1] }}"
    npm_auth_token: "{{ cicd_user_npm_auth_token }}"

    aws_profile: "{{ general_aws_profile }}"
    aws_access_key_id: "{{ cicd_user_aws_access_key_id }}"
    aws_secret_access_key: "{{ cicd_user_aws_secret_access_key }}"

  roles:
    - role: print_inventory_hostname

    - role: create_new_user

    - role: generate_ssh_keys
      tags:
        - ssh

    - role: install_general_dependencies
      dependency_git_install: yes
      dependency_make_install: yes
      tags:
        - dependencies
      when: "inventory_hostname != 'local'"

    - role: install_python_dependencies
      tags:
        - dependencies
        - python

    - role: install_node_dependencies
      tags:
        - dependencies
        - node

    - role: setup_playbooks
      tags:
        - playbooks

- import_playbook: sensitive_files/download.yml
