- name: deploy knightwatcherbot to aws lambda
  hosts: local
  gather_facts: no

  vars:
    repo_name: knightwatcherbot
    service_name: bot-suddi-io-lambda
    deployed_link: https://bot.suddi.io
    repo_url: "{{ github_account }}/{{ repo_name }}.git"
    aws_region: ap-northeast-1
    runtime: nodejs4.3
    api_module: lib/app
    api_version: production
    timeout: 30
    memory: 128
    sg_ids: ""
    subnet_ids: ""

  roles:
    - role: deploy_lambda_function
      tags:
        - lambda
        - claudia
