- name: deploy knightwatcherbot to aws lambda
  hosts: local
  gather_facts: no

  vars:
    service_name: "{{ knightwatcher_service_name }}"
    service_url: "{{ knightwatcher_service_url }}"

    repo_name: knightwatcherbot
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

    deploy_user: "{{ runtime_user }}"
    deploy_node_version: v4

    aws_profile: "{{ general_aws_profile }}"
    aws_region: ap-northeast-1
    aws_lambda_runtime: nodejs4.3

  roles:
    - role: assert_node_version
      expected_node_version: "{{ deploy_node_version }}"

    - role: empty_work_dir

    - role: deploy_lambda_function
      tags:
        - lambda
        - claudia

    - role: empty_work_dir

    - role: notify_knightwatcher
      message_username: "{{ deploy_user }}"
      message_type: deploy
      message_link: "{{ service_url }}"
      message_repo_name: "{{ repo_name }}"


