- name: deploy knightwatcherbot to aws lambda
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ knightwatcher_project_name }}"
    service_name: "{{ knightwatcher_service_prefix }}lambda"
    service_url: "{{ knightwatcher_service_url }}"

    repo_name: knightwatcherbot
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

    user: "{{ runtime_user }}"

    node_version: v4

    aws_profile: "{{ general_aws_profile }}"
    aws_region: ap-northeast-1
    aws_lambda_runtime: nodejs4.3
    aws_lambda_environment_variables: TABLENAME={{ knightwatcher_config_tablename }},TELEGRAM_API_KEY={{ knightwatcher_config_telegram_api_key }},DEFAULT_NOTIFIER={{ knightwatcher_config_default_notifier }}

  roles:
    - role: empty_work_dir

    - role: deploy_lambda_function
      create_usage_plan: yes
      create_api_key: no
      tags:
        - lambda
        - claudia

    - role: empty_work_dir

    - role: notify_knightwatcher
      message_username: "{{ user }}"
      message_type: deploy
      message_link: "{{ service_url }}"
      message_repo_name: "{{ service_name }}"
