- name: publish "{{ package_name }}" to npm
  hosts: local
  gather_facts: no

  vars:
    repo_name: "{{ package_name }}"
    repo_url: "{{ github_account }}/{{ package_name }}.git"

  tasks:
    - name: publish {{ repo_name }} to npm
      include_role:
        name: publish_npm_package
