- name: handle sensitive files to/from s3
  hosts: local
  gather_facts: no

  vars:
    project: ansible
    service: "{{ project }}-sensitive-files"
    bucket_name: vault.suddi.io
    aws_region: ap-northeast-1
    acl: private
    perform_action: "{{ sensitive_files_action | default('upload') }}"
    sensitive_files:
      - group_vars/all/vault.encrypted.yml
      - inventory.ini

  tasks:
    - name: check if {{ bucket_name }} s3 bucket exists
      command: aws s3api head-bucket
        --bucket {{ bucket_name }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
      register: head_bucket_result
      failed_when: "head_bucket_result.stderr and
        'Not Found' not in head_bucket_result.stderr"

    - name: create {{ bucket_name }} s3 bucket
      command: aws s3api create-bucket
        --acl {{ acl }}
        --bucket {{ bucket_name }}
        --create-bucket-configuration LocationConstraint={{ aws_region }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
      when: "perform_action == 'upload' and
        'Not Found' in head_bucket_result.stderr"

    - name: set versioning for {{ bucket_name }} s3 bucket
      command: aws s3api put-bucket-versioning
        --bucket {{ bucket_name }}
        --versioning-configuration MFADelete=Disabled,Status=Enabled
        --profile {{ aws_profile }}
        --region {{ aws_region }}
      when: "perform_action == 'upload' and
        'Not Found' in head_bucket_result.stderr"

    - name: set tags for {{ bucket_name }} s3 bucket
      command: aws s3api put-bucket-tagging
        --bucket {{ bucket_name }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        --tagging TagSet=[{Key=project,Value={{ project }}},{Key=service,Value={{ service }}},{Key=deployment_method,Value={{ deployment_method }}}]
      when: "perform_action == 'upload' and
        'Not Found' in head_bucket_result.stderr"

    - name: put objects to {{ bucket_name }} s3 bucket
      command: aws s3api put-object
        --acl {{ acl }}
        --body {{ inventory_dir }}/{{ item }}
        --bucket {{ bucket_name }}
        --key {{ item }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        --server-side-encryption AES256
        --tagging project={{ project }}&service={{ service }}&deployment_method={{ deployment_method }}
      with_items: "{{ sensitive_files }}"
      when: "perform_action == 'upload'"

    - name: get objects from {{ bucket_name }} s3 bucket
      command: aws s3api get-object
        --bucket {{ bucket_name }}
        --key {{ item }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        "{{ inventory_dir }}/{{ item }}"
      with_items: "{{ sensitive_files }}"
      when: "perform_action == 'download'"
