- name: upload vault files to s3
  hosts: local
  gather_facts: no

  vars:
    bucket_name: ansible-vault
    bucket_tags:
      deployment_method: ansible
      service: ansible-vault
      project: ansible
    aws_profile: ap-northeast-1
    action: "{{ vault_files_action | default('upload') }}"

  tasks:
    - name: check if {{ bucket_name }} s3 bucket exists
      command: aws s3 ls
      register: s3_ls_result

    - name: create {{ bucket_name }} s3 bucket
      s3_bucket:
        name: "{{ bucket_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: present
        tags: "{{ bucket_tags }}"
      when: "{{ action }} == 'upload' and
        '{{ bucket_name }}' not in s3_ls_result.stdout"

    - name: sync object to {{ bucket_name }} s3 bucket
      s3_sync:
        bucket: "{{ bucket_name }}"
        file_change_strategy: date_size
        file_root: "{{ inventory_dir }}/group_vars"
        include: "*.encrypted.yml"
        mode: push
        permission: private
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
      when: "{{ action }} == 'upload'"

    - name: sync object from {{ bucket_name }} s3 bucket
      s3_sync:
        bucket: "{{ bucket_name }}"
        file_change_strategy: date_size
        file_root: "{{ inventory_dir }}/group_vars"
        include: "*.encrypted.yml"
        mode: pull
        permission: private
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        object: "{{ object_path }}"
        src: "{{ source_path }}"
        mode: put
      when: "{{ action }} == 'download'"
