- name: deploy kobebot to heroku
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ kobe_project_name }}"
    service_name: "{{ project_name }}-heroku-app"
    service_url: "{{ kobe_service_url }}"

    repo_name: kobebot
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

    user: "{{ runtime_user }}"

    heroku_region: us
    heroku_app_name: suddi-kobebot
    heroku_app_environment_variables: MICROSOFT_APP_ID={{ kobe_config_microsoft_app_id }}\nMICROSOFT_APP_PASSWORD={{ kobe_config_microsoft_app_password }}\nNODE_ENV=production

    node_version: v12

  roles:
    - role: nodejs/assert_node_version
      expected_node_version: "{{ node_version }}"

    - role: utils/empty_work_dir

    - role: heroku/deploy_heroku_app
      tags:
          - heroku

    - role: utils/empty_work_dir

    - role: utils/notify_knightwatcher
      message_username: "{{ user }}"
      message_type: deploy
      message_link: "{{ service_url }}"
      message_repo_name: "{{ repo_name }}"
