- name: install zsh
  package:
    name: zsh
    state: present

- name: add .zshrc to ~/.zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: "0644"

- name: clone oh-my-zsh repo
  git:
    repo: "{{ dependency_oh_my_zsh_url }}"
    dest: "{{ dependency_oh_my_zsh_dir }}"
    force: yes
    update: yes
    version: "{{ dependency_oh_my_zsh_version }}"