- name: verify that version_increment_level is appropriate
  assert:
    that:
      - "npm_package_version_increment_level in ['major', 'minor', 'patch']"

- name: get source code
  git:
    repo: "{{ repo_url }}"
    dest: "{{ work_dir }}"
    force: yes
    version: "{{ repo_version }}"

# - name: switch to .nvmrc node version
#   shell: nvm use
#   args:
#     chdir: "{{ work_dir }}"
#     removes: .nvmrc

- name: install npm dependencies for build
  command: npm install
  args:
    chdir: "{{ work_dir }}"

- name: run npm test
  command: npm test
  args:
    chdir: "{{ work_dir }}"

- name: increment package version
  command: npm version {{ npm_package_version_increment_level }}
  args:
    chdir: "{{ work_dir }}"

- name: commit package version increment
  command: git push origin {{ repo_version }}
  args:
    chdir: "{{ work_dir }}"

- name: publish npm package
  command: npm publish
  args:
    chdir: "{{ work_dir }}"
