- name: deploy knightwatcherbot to aws lambda
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ knightwatcher_project_name }}"
    service_name: "{{ project_name }}-lambda"
    service_url: "{{ knightwatcher_service_url }}"

    repo_name: knightwatcherbot
    repo_url: "{{ github_account }}/{{ repo_name }}.git"

    user: "{{ runtime_user }}"

    node_version: v12

    aws_lambda_runtime: nodejs12.x
    aws_lambda_environment_variables: REGION={{ knightwatcher_config_aws_region }},TABLENAME={{ knightwatcher_config_tablename }},TELEGRAM_API_KEY={{ knightwatcher_config_telegram_api_key }},DEFAULT_NOTIFIER={{ knightwatcher_config_default_notifier }}

  roles:
    - role: nodejs/assert_node_version
      expected_node_version: "{{ node_version }}"

    - role: utils/empty_work_dir

    - role: nodejs/deploy_claudia_app
      create_usage_plan: yes
      create_api_key: no
      tags:
        - lambda
        - claudia

    - role: utils/empty_work_dir

    - role: utils/notify_knightwatcher
      message_username: "{{ user }}"
      message_type: deploy
      message_link: "{{ service_url }}"
      message_repo_name: "{{ repo_name }}"
