- name: setup local machine
  hosts: local

  vars:
    user: "{{ default_user }}"
    user_email: "{{ default_user_email }}"
    user_home_dir: "~"
    user_shell: /bin/zsh
    user_shell_rc_file: "{{ user_home_dir }}/.zshrc"

    python_versions:
      - "3.8.2"
      - "2.7.17"
    python_default_version: "{{ python_versions[0] }}"

    node_versions:
      - "12"
      - "10"
      - "8"
    node_default_version: "{{ node_versions[0] }}"

    aws_access_key_id: "{{ default_user_aws_access_key_id }}"
    aws_secret_access_key: "{{ default_user_aws_secret_access_key }}"

  roles:
    - role: general/install_macos_dependencies

    - role: git/install_git

    - role: general/install_general_dependencies
      dependency_make_install: yes

    - role: user/generate_ssh_keys
      
    - role: shell/setup_zsh

    - role: python/install_python_dependencies
      add_rc_initialization: false

    - role: nodejs/install_node_dependencies
      add_rc_initialization: false
