- name: check if {{ aws_s3_bucket_name }} s3 bucket exists
  command: aws s3api head-bucket
    --profile {{ aws_profile }}
    --region {{ aws_region }}
    --bucket {{ aws_s3_bucket_name }}

- name: put objects to {{ aws_s3_bucket_name }} s3 bucket
  command: aws s3api put-object
    --profile {{ aws_profile }}
    --region {{ aws_region }}
    --bucket {{ aws_s3_bucket_name }}
    --acl {{ aws_s3_acl }}
    --body {{ upload_root_dir }}/{{ item }}
    --key {{ item }}
    {% if server_side_encryption is defined %}
      --server-side-encryption AES256
    {% endif %}
    --tagging project={{ project_name }}&service={{ service_name }}&deployment_method={{ deployment_method }}
  with_items: "{{ files }}"
  when: files is defined and files | length > 0

- name: copy folder to {{ aws_s3_bucket_name }} s3 bucket
  command: aws s3 cp {{ upload_root_dir }}/{{ folder }} s3://{{ aws_s3_bucket_name }}/
    --recursive
    --profile {{ aws_profile }}
    --region {{ aws_region }}
    --acl {{ aws_s3_acl }}
    {% if server_side_encryption is defined %}
      --sse AES256
    {% endif %}
    {% if exclude is defined %}
      --exclude "{{ exclude }}"
    {% endif %}
  when: folder is defined

