- name: provision resources for sites under suddi.io
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ general_project_name }}-io"

  roles:
    - role: aws/execute_cloudformation_stack
      aws_stack_name: "{{ project_name }}-stack"
      aws_stack_file_path: "{{ files_dir }}/cloudformation/suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ general_domain }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
      service_name: "{{ project_name }}"

    - role: aws/execute_cloudformation_stack
      aws_stack_name: github-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/github_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ github_domain }}
          ParameterKey=RouteUrl,ParameterValue={{ github_url }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
      service_name: github-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: lambda-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/lambda_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ lambda_domain }}
      service_name: lambda-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: linkedin-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/linkedin_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ linkedin_domain }}
          ParameterKey=RouteUrl,ParameterValue={{ linkedin_url }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
      service_name: linkedin-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: vault-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/vault_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=Project,ParameterValue={{ project_name }}
          ParameterKey=Service,ParameterValue={{ vault_domain }}
      service_name: vault-{{ project_name }}
