- name: provision resources for sites under suddi.io
  hosts: local
  gather_facts: no

  vars:
    project_name: "{{ general_project_name }}-io"
    service_url: "{{ general_service_url }}"

    repo_name: suddi.github.io

    user: "{{ runtime_user }}"

  roles:
    - role: aws/execute_cloudformation_stack
      aws_stack_name: "{{ project_name }}-stack"
      aws_stack_file_path: "{{ files_dir }}/cloudformation/suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=ProjectName,ParameterValue={{ project_name }}
          ParameterKey=ServiceName,ParameterValue={{ project_name }}
          ParameterKey=Domain,ParameterValue={{ general_domain }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
          ParameterKey=MailAdministrator,ParameterValue=admin@{{ general_domain }}
      service_name: "{{ project_name }}"

    - role: aws/execute_cloudformation_stack
      aws_stack_name: github-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/github_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=ProjectName,ParameterValue={{ project_name }}
          ParameterKey=ServiceName,ParameterValue=github-{{ project_name }}
          ParameterKey=Domain,ParameterValue={{ github_domain }}
          ParameterKey=RouteUrl,ParameterValue={{ github_url }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
      service_name: github-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: lambda-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/lambda_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=ProjectName,ParameterValue={{ project_name }}
          ParameterKey=ServiceName,ParameterValue=lambda-{{ project_name }}
          ParameterKey=Domain,ParameterValue={{ lambda_domain }}
      service_name: lambda-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: linkedin-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/linkedin_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=ProjectName,ParameterValue={{ project_name }}
          ParameterKey=ServiceName,ParameterValue=linkedin-{{ project_name }}
          ParameterKey=Domain,ParameterValue={{ linkedin_domain }}
          ParameterKey=RouteUrl,ParameterValue={{ linkedin_url }}
          ParameterKey=HostedZone,ParameterValue={{ general_domain }}.
      service_name: linkedin-{{ project_name }}

    - role: aws/execute_cloudformation_stack
      aws_stack_name: vault-{{ project_name }}-stack
      aws_stack_file_path: "{{ files_dir }}/cloudformation/vault_suddi_io.yml"
      aws_stack_parameters: |
          ParameterKey=ProjectName,ParameterValue={{ project_name }}
          ParameterKey=ServiceName,ParameterValue=vault-{{ project_name }}
          ParameterKey=Domain,ParameterValue={{ vault_domain }}
      service_name: vault-{{ project_name }}

    - role: utils/notify_knightwatcher
      message_username: "{{ user }}"
      message_type: deploy
      message_link: "{{ service_url }}"
      message_repo_name: "{{ repo_name }}"
