- name: download sensitive files from s3
  hosts: local
  gather_facts: no

  vars:
    bucket_name: vault.suddi.io
    aws_region: ap-northeast-1
    sensitive_files:
      - group_vars/all/vault.encrypted.yml
      - inventory.ini

  tasks:
    - name: get objects from {{ bucket_name }} s3 bucket
      command: aws s3api get-object
        --bucket {{ bucket_name }}
        --key {{ item }}
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        "{{ inventory_dir }}/{{ item }}"
      with_items: "{{ sensitive_files }}"
