- name: download sensitive files from s3
  hosts: local
  gather_facts: no

  vars:
    project_name: ansible
    service_name: "{{ project_name }}-sensitive-files"

    aws_s3_bucket_name: "{{ vault_domain }}"

    download_root_dir: "{{ project_root_dir }}"
    files: "{{ sensitive_files }}"

  roles:
    - role: aws/get_object_from_s3_bucket

