- name: upload sensitive files to s3
  hosts: local
  gather_facts: no

  vars:
    project_name: ansible
    service_name: "{{ project_name }}-sensitive-files"

    aws_s3_bucket_name: "{{ vault_domain }}"
    aws_s3_acl: private

    upload_root_dir: "{{ project_root_dir }}"

    files: "{{ sensitive_files }}"

  tasks:
    - name: check if {{ aws_s3_bucket_name }} s3 bucket exists
      command: aws s3api head-bucket
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        --bucket {{ aws_s3_bucket_name }}

    - name: put objects to {{ aws_s3_bucket_name }} s3 bucket
      command: aws s3api put-object
        --profile {{ aws_profile }}
        --region {{ aws_region }}
        --bucket {{ aws_s3_bucket_name }}
        --acl {{ aws_s3_acl }}
        --body {{ upload_root_dir }}/{{ item }}
        --key {{ item }}
        --server-side-encryption AES256
        --tagging project={{ project_name }}&service={{ service_name }}&deployment_method={{ deployment_method }}
      with_items: "{{ files }}"
