- name: upload sensitive files to s3
  hosts: local
  gather_facts: no

  vars:
    project_name: ansible
    service_name: "{{ project_name }}-sensitive-files"

    aws_s3_bucket_name: "{{ vault_domain }}"
    aws_s3_acl: private

    upload_root_dir: "{{ project_root_dir }}"
    files: "{{ sensitive_files }}"

  roles:
    - role: aws/put_object_to_s3_bucket
      server_side_encryption: yes
